name: Trivy Security Scan

on:
 workflow_dispatch:

jobs:
  trivy-scan:
    name: Run Trivy Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy on terraform
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: ./terraform
          format: table
          scanners: misconfig,secret
          severity: CRITICAL,HIGH
          exit-code: 0
      - name: Run Trivy on k8s
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: ./k8s
          format: table
          scanners: misconfig,secret
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Run Trivy on apps
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: ./apps
          format: table
          scanners: vuln,misconfig,secret
          severity: CRITICAL,HIGH
          exit-code: 0

          
